<?php

$zenDiscount = time() <= strtotime('2026-05-05 23:59:59') ? 0.5 : 1.0;

return [
    'items' => [
        'monthly_card' => [
            'id' => 'monthly_card',
            'name' => 'Thẻ Tháng',
            'description' => 'Đặc quyền 30 ngày',
            'icon' => '🗓️',
            'image' => 'https://placehold.co/400x300/1e1e1e/white?text=The+Thang',
            'price_wpoint' => 200,
            'price_wcoin' => null,
            'feecallback_item_id' => 280, // This is the old legacy ID, 28 RMB package
            'tags' => ['20,000 KC/ngày', 'EXP +50%', 'Túi đầy +100', '30 ngày'],
            'badge' => 'HOT',
            'allow_gift' => true,
            'limit_per_user' => null,
        ],
        'wcoin_starter' => [
            'id' => 'wcoin_starter',
            'name' => 'Starter (2M Kim Cương)',
            'description' => 'Gói Starter ưu đãi thời gian. Nhận ngay 2M Kim Cương. Mỗi nhân vật chỉ được mua 1 lần duy nhất.',
            'icon' => '💎',
            'image' => 'https://placehold.co/400x300/1e1e1e/white?text=STARTER+2M',
            'price_wpoint' => null,
            'price_wcoin' => 100,
            'feecallback_item_id' => null,
            'is_direct_kc' => true,
            'base_kc_yield' => 2000000,
            'tags' => ['Tân Thủ', 'Lim. 1 Lần'],
            'badge' => 'STARTER',
            'allow_gift' => false,
            'limit_per_user' => 1,
            'is_variable' => false,
        ],
        'wcoin_growth' => [
            'id' => 'wcoin_growth',
            'name' => 'Growth (8M Kim Cương)',
            'description' => 'Gói Growth tăng trưởng. Giúp vượt early bottleneck. Nhận ngay 8M Kim Cương. Mỗi nhân vật mua 1 lần.',
            'icon' => '💎',
            'image' => 'https://placehold.co/400x300/1e1e1e/white?text=GROWTH+8M',
            'price_wpoint' => null,
            'price_wcoin' => 250,
            'feecallback_item_id' => null,
            'is_direct_kc' => true,
            'base_kc_yield' => 8000000,
            'tags' => ['Phổ Biến', 'Lim. 1 Lần'],
            'badge' => 'GROWTH',
            'allow_gift' => false,
            'limit_per_user' => 1,
            'is_variable' => false,
        ],
        'wcoin_jumpstart' => [
            'id' => 'wcoin_jumpstart',
            'name' => 'Jumpstart (20M Kim Cương)',
            'description' => 'Gói Jumpstart tức thì. Nhận ngay 20M Kim Cương. Mỗi nhân vật chỉ được mua 1 lần duy nhất.',
            'icon' => '💎',
            'image' => 'https://placehold.co/400x300/1e1e1e/white?text=JUMPSTART+20M',
            'price_wpoint' => null,
            'price_wcoin' => 600,
            'feecallback_item_id' => null,
            'is_direct_kc' => true,
            'base_kc_yield' => 20000000,
            'tags' => ['Siêu Cấp', 'Lim. 1 Lần'],
            'badge' => 'JUMPSTART',
            'allow_gift' => false,
            'limit_per_user' => 1,
            'is_variable' => false,
        ],
        'tom_to_kc_10m' => [
            'id' => 'tom_to_kc_10m',
            'name' => '10M Kim Cương (Quà tri ân)',
            'description' => 'Nhận 10,000,000 Kim Cương (Cao hơn gói Growth). Giúp vượt map sớm & mở build nhanh hơn. Giới hạn 1 lần.',
            'icon' => '💎',
            'image' => 'https://placehold.co/400x300/1e1e1e/white?text=10M+KC',
            'price_wpoint' => null,
            'price_wcoin' => null,
            'price_tom' => 10,
            'feecallback_item_id' => null,
            'is_direct_kc' => true,
            'base_kc_yield' => 10000000,
            'tags' => ['Lim. 1 Lần'],
            'badge' => '⚡ ƯU ĐÃI',
            'allow_gift' => false,
            'limit_per_user' => 1,
            'is_variable' => false,
        ],
        'zen_card_1d' => [
            'id' => 'zen_card_1d',
            'name' => 'ZEN Mode +50% (1 ngày)',
            'description' => 'Tăng 50% ZEN drop từ quái/treo máy. Hiệu lực toàn đội.',
            'icon' => '6.png',
            'price_diamond' => 200000000 * $zenDiscount,
            'feecallback_item_id' => 88801,
            'tags' => ['ZEN +50%', '1 ngày', 'Hiệu Lực Toàn Đội'],
            'badge' => null,
            'allow_gift' => false,
            'is_zen_card' => true,
        ],
        'zen_card_3d' => [
            'id' => 'zen_card_3d',
            'name' => 'ZEN Mode +50% (3 ngày)',
            'description' => 'Tăng 50% ZEN drop từ quái/treo máy. Hiệu lực toàn đội.',
            'icon' => '3.png',
            'price_diamond' => 575000000 * $zenDiscount,
            'feecallback_item_id' => 88803,
            'tags' => ['ZEN +50%', '3 ngày', 'Hiệu Lực Toàn Đội'],
            'badge' => 'EVENT',
            'allow_gift' => false,
            'is_zen_card' => true,
        ],
        'zen_card_7d' => [
            'id' => 'zen_card_7d',
            'name' => 'ZEN Mode +50% (7 ngày)',
            'description' => 'Tăng 50% ZEN drop từ quái/treo máy. Hiệu lực toàn đội.',
            'icon' => '5.png',
            'price_diamond' => 1350000000 * $zenDiscount,
            'feecallback_item_id' => 88807,
            'tags' => ['ZEN +50%', '7 ngày', 'Hiệu Lực Toàn Đội'],
            'badge' => '🏆 ĐUA TOP',
            'allow_gift' => false,
            'is_zen_card' => true,
        ],

        'lifetime_card' => [
            'id' => 'lifetime_card',
            'name' => 'Đặc Quyền Trọn Đời',
            'description' => '+100% ZEN, tăng mạnh drop map. Mua 1 lần duy nhất.',
            'icon' => '5.png',
            'price_tom' => 20,
            'feecallback_item_id' => 88899,
            'tags' => ['X2 ZEN', 'Tăng Drop Map', 'Vĩnh viễn'],
            'badge' => '👑 TRỌN ĐỜI',
            'allow_gift' => false,
            'limit_per_user' => 1,
            'is_lifetime_card' => true,
        ],
        'tom_title_chiton' => [
            'id' => 'tom_title_chiton',
            'name' => 'Danh Hiệu Chí Tôn',
            'description' => 'Danh hiệu độc quyền Mùa Hồi Quy, lực chiến đỉnh (~1.5 triệu), vĩnh viễn. Nhận Lệnh Bài qua thư trong game, dùng để kích hoạt danh hiệu. Mỗi nhân vật 1 lần.',
            'icon' => '👑',
            'image' => 'https://cdn.ccgame.org/h5/muh5/resource/resource/image/chenghao/ch_mu_72.png',
            'price_wpoint' => null,
            'price_wcoin' => null,
            'price_tom' => 80,
            'game_item_id' => 380077,
            'feecallback_item_id' => 380077,
            'tags' => ['Danh Hiệu', 'Lực Chiến Đỉnh', 'Vĩnh Viễn', 'Mùa Hồi Quy'],
            'badge' => '👑 CHÍ TÔN',
            'allow_gift' => false,
            'limit_per_user' => 1,
            'is_variable' => false,
        ],
        'pet_loi_trach' => [
            'id' => 'pet_loi_trach',
            'name' => '★Truyền Thuyết★ Lôi Trạch',
            'description' => 'Pet huyền thoại Truyền Thuyết, buff ATK/HP/DEF mạnh, lực chiến vượt trội. Độc quyền Mùa Hồi Quy, mỗi nhân vật 1 con.',
            'icon' => 'pet',
            'image' => '/client/resource/res/fairy/body/pet_020_0s.png',
            'game_item_id' => 500052,
            'price_diamond' => null,
            'cost_diamond_block' => null, // Dynamic: escalating price
            'price_wpoint' => null,
            'price_wcoin' => null,
            'price_tom' => 40,
            'feecallback_item_id' => 500052,
            'is_escalating_price' => false,
            'limit_per_server' => null,
            'tags' => ['Legendary', 'Pet Huyền Thoại', 'Mùa Hồi Quy'],
            'badge' => '🔥 ĐỘC QUYỀN',
            'allow_gift' => false,
            'limit_per_user' => 1,
            'is_pet' => true,
            'pet_stats' => [
                ['label' => 'ATK Cộng', 'value' => '+15%', 'icon' => '⚔️'],
                ['label' => 'HP Cộng', 'value' => '+12%', 'icon' => '❤️'],
                ['label' => 'DEF Cộng', 'value' => '+10%', 'icon' => '🛡️'],
                ['label' => 'Phẩm Chất', 'value' => 'Truyền Thuyết', 'icon' => '⭐'],
                ['label' => 'Kỹ Năng', 'value' => 'Lôi Kích / Điện Hào', 'icon' => '⚡'],
                ['label' => 'Loại', 'value' => 'Tấn Công', 'icon' => '🐉'],
            ],
        ],
        'pet_doa_thien_su' => [
            'id' => 'pet_doa_thien_su',
            'name' => '★Truyền Thuyết★ Đọa Thiên Sứ',
            'description' => 'Năng lượng bóng tối bủa vây. Thông tin kỹ năng sẽ cập nhật khi mở bán chính thức.',
            'icon' => 'pet',
            'image' => '/client/resource/res/item/500021.png', // Thay ảnh khi có
            'game_item_id' => null,
            'price_diamond' => null,
            'price_wpoint' => null,
            'price_wcoin' => null,
            'price_tom' => null,
            'feecallback_item_id' => null,
            'is_escalating_price' => false,
            'limit_per_server' => 5,
            'tags' => ['Legendary', 'Pet Mystery', 'Bóng Tối'],
            'badge' => 'NEW',
            'allow_gift' => false,
            'limit_per_user' => null,
            'is_pet' => true,
            'is_coming_soon' => true, // Flag Ẩn thông số
            'pet_stats' => [],
        ],
    ],
];
