<?php

$zenDiscount = time() <= strtotime('2026-05-05 23:59:59') ? 0.5 : 1.0;

return [
    'items' => [
        'monthly_card' => [
            'id' => 'monthly_card',
            'name' => 'Thẻ Tháng',
            'description' => 'Đặc quyền 30 ngày',
            'icon' => '🗓️',
            'image' => 'https://placehold.co/400x300/1e1e1e/white?text=The+Thang',
            'price_wpoint' => 200,
            'price_wcoin' => null,
            'feecallback_item_id' => 280, // This is the old legacy ID, 28 RMB package
            'tags' => ['20,000 KC/ngày', 'EXP +50%', 'Túi đầy +100', '30 ngày'],
            'badge' => 'HOT',
            'allow_gift' => true,
            'limit_per_user' => null,
        ],
        'wcoin_starter' => [
            'id' => 'wcoin_starter',
            'name' => 'Starter (2M Kim Cương)',
            'description' => 'Gói Starter ưu đãi thời gian. Nhận ngay 2M Kim Cương. Mỗi nhân vật chỉ được mua 1 lần duy nhất.',
            'icon' => '💎',
            'image' => 'https://placehold.co/400x300/1e1e1e/white?text=STARTER+2M',
            'price_wpoint' => null,
            'price_wcoin' => 100,
            'feecallback_item_id' => null,
            'is_direct_kc' => true,
            'base_kc_yield' => 2000000,
            'tags' => ['Tân Thủ', 'Lim. 1 Lần'],
            'badge' => 'STARTER',
            'allow_gift' => false,
            'limit_per_user' => 1,
            'is_variable' => false,
        ],
        'wcoin_growth' => [
            'id' => 'wcoin_growth',
            'name' => 'Growth (8M Kim Cương)',
            'description' => 'Gói Growth tăng trưởng. Giúp vượt early bottleneck. Nhận ngay 8M Kim Cương. Mỗi nhân vật mua 1 lần.',
            'icon' => '💎',
            'image' => 'https://placehold.co/400x300/1e1e1e/white?text=GROWTH+8M',
            'price_wpoint' => null,
            'price_wcoin' => 250,
            'feecallback_item_id' => null,
            'is_direct_kc' => true,
            'base_kc_yield' => 8000000,
            'tags' => ['Phổ Biến', 'Lim. 1 Lần'],
            'badge' => 'GROWTH',
            'allow_gift' => false,
            'limit_per_user' => 1,
            'is_variable' => false,
        ],
        'wcoin_jumpstart' => [
            'id' => 'wcoin_jumpstart',
            'name' => 'Jumpstart (20M Kim Cương)',
            'description' => 'Gói Jumpstart tức thì. Nhận ngay 20M Kim Cương. Mỗi nhân vật chỉ được mua 1 lần duy nhất.',
            'icon' => '💎',
            'image' => 'https://placehold.co/400x300/1e1e1e/white?text=JUMPSTART+20M',
            'price_wpoint' => null,
            'price_wcoin' => 600,
            'feecallback_item_id' => null,
            'is_direct_kc' => true,
            'base_kc_yield' => 20000000,
            'tags' => ['Siêu Cấp', 'Lim. 1 Lần'],
            'badge' => 'JUMPSTART',
            'allow_gift' => false,
            'limit_per_user' => 1,
            'is_variable' => false,
        ],
        'tom_to_kc_10m' => [
            'id' => 'tom_to_kc_10m',
            'name' => '10M Kim Cương (Quà tri ân)',
            'description' => 'Nhận 10,000,000 Kim Cương (Cao hơn gói Growth). Giúp vượt map sớm & mở build nhanh hơn. Giới hạn 1 lần.',
            'icon' => '💎',
            'image' => 'https://placehold.co/400x300/1e1e1e/white?text=10M+KC',
            'price_wpoint' => null,
            'price_wcoin' => null,
            'price_tom' => 10,
            'feecallback_item_id' => null,
            'is_direct_kc' => true,
            'base_kc_yield' => 10000000,
            'tags' => ['Lim. 1 Lần'],
            'badge' => '⚡ ƯU ĐÃI',
            'allow_gift' => false,
            'limit_per_user' => 1,
            'is_variable' => false,
        ],
        'zen_card_1d' => [
            'id' => 'zen_card_1d',
            'name' => 'ZEN Mode +50% (1 ngày)',
            'description' => 'Tăng 50% ZEN drop từ quái/treo máy. Hiệu lực toàn đội.',
            'icon' => '6.png',
            'price_diamond' => 200000000 * $zenDiscount,
            'feecallback_item_id' => 88801,
            'tags' => ['ZEN +50%', '1 ngày', 'Hiệu Lực Toàn Đội'],
            'badge' => null,
            'allow_gift' => false,
            'is_zen_card' => true,
        ],
        'zen_card_3d' => [
            'id' => 'zen_card_3d',
            'name' => 'ZEN Mode +50% (3 ngày)',
            'description' => 'Tăng 50% ZEN drop từ quái/treo máy. Hiệu lực toàn đội.',
            'icon' => '3.png',
            'price_diamond' => 575000000 * $zenDiscount,
            'feecallback_item_id' => 88803,
            'tags' => ['ZEN +50%', '3 ngày', 'Hiệu Lực Toàn Đội'],
            'badge' => 'EVENT',
            'allow_gift' => false,
            'is_zen_card' => true,
        ],
        'zen_card_7d' => [
            'id' => 'zen_card_7d',
            'name' => 'ZEN Mode +50% (7 ngày)',
            'description' => 'Tăng 50% ZEN drop từ quái/treo máy. Hiệu lực toàn đội.',
            'icon' => '5.png',
            'price_diamond' => 1350000000 * $zenDiscount,
            'feecallback_item_id' => 88807,
            'tags' => ['ZEN +50%', '7 ngày', 'Hiệu Lực Toàn Đội'],
            'badge' => '🏆 ĐUA TOP',
            'allow_gift' => false,
            'is_zen_card' => true,
        ],

        'lifetime_card' => [
            'id' => 'lifetime_card',
            'name' => 'Đặc Quyền Trọn Đời',
            'description' => '+100% ZEN, tăng mạnh drop map. Mua 1 lần duy nhất.',
            'icon' => '5.png',
            'price_tom' => 20,
            'feecallback_item_id' => 88899,
            'tags' => ['X2 ZEN', 'Tăng Drop Map', 'Vĩnh viễn'],
            'badge' => '👑 TRỌN ĐỜI',
            'allow_gift' => false,
            'limit_per_user' => 1,
            'is_lifetime_card' => true,
        ],
        'tom_title_chiton' => [
            'id' => 'tom_title_chiton',
            'name' => 'Danh Hiệu Chí Tôn',
            'description' => 'Danh hiệu độc quyền Mùa Hồi Quy, lực chiến đỉnh (~1.5 triệu), vĩnh viễn. Nhận Lệnh Bài qua thư trong game, dùng để kích hoạt danh hiệu. Mỗi nhân vật 1 lần.',
            'icon' => '👑',
            'image' => 'https://cdn.ccgame.org/h5/muh5/resource/resource/image/chenghao/ch_mu_72.png',
            'price_wpoint' => null,
            'price_wcoin' => null,
            'price_tom' => 80,
            'game_item_id' => 380077,
            'feecallback_item_id' => 380077,
            'tags' => ['Danh Hiệu', 'Lực Chiến Đỉnh', 'Vĩnh Viễn', 'Mùa Hồi Quy'],
            'badge' => '👑 CHÍ TÔN',
            'allow_gift' => false,
            'limit_per_user' => 1,
            'is_variable' => false,
        ],
        'pet_loi_trach' => [
            'id' => 'pet_loi_trach',
            'name' => '★Truyền Thuyết★ Lôi Trạch',
            'description' => 'Pet huyền thoại Truyền Thuyết, buff ATK/HP/DEF mạnh, lực chiến vượt trội. Độc quyền Mùa Hồi Quy, mỗi nhân vật 1 con.',
            'icon' => 'pet',
            'image' => '/client/resource/res/fairy/body/pet_020_0s.png',
            'game_item_id' => 500052,
            'price_diamond' => null,
            'cost_diamond_block' => null, // Dynamic: escalating price
            'price_wpoint' => null,
            'price_wcoin' => null,
            'price_tom' => 40,
            'feecallback_item_id' => 500052,
            'is_escalating_price' => false,
            'limit_per_server' => null,
            'tags' => ['Legendary', 'Pet Huyền Thoại', 'Mùa Hồi Quy'],
            'badge' => '🔥 ĐỘC QUYỀN',
            'allow_gift' => false,
            'limit_per_user' => 1,
            'is_pet' => true,
            'pet_stats' => [
                ['label' => 'ATK Cộng', 'value' => '+15%', 'icon' => '⚔️'],
                ['label' => 'HP Cộng', 'value' => '+12%', 'icon' => '❤️'],
                ['label' => 'DEF Cộng', 'value' => '+10%', 'icon' => '🛡️'],
                ['label' => 'Phẩm Chất', 'value' => 'Truyền Thuyết', 'icon' => '⭐'],
                ['label' => 'Kỹ Năng', 'value' => 'Lôi Kích / Điện Hào', 'icon' => '⚡'],
                ['label' => 'Loại', 'value' => 'Tấn Công', 'icon' => '🐉'],
            ],
        ],
        'pet_doa_thien_su' => [
            'id' => 'pet_doa_thien_su',
            'name' => '★Truyền Thuyết★ Đọa Thiên Sứ',
            'description' => 'Pet Truyền Thuyết tạo hình bóng tối mới nhất, buff ATK/HP/DEF mạnh, lực chiến vượt trội. Mỗi nhân vật 1 con.',
            'icon' => 'pet',
            'image' => '/client/resource/res/fairy/body/pet_021_0s.png',
            'game_item_id' => 500053,
            'price_diamond' => null,
            'price_wpoint' => null,
            'price_wcoin' => null,
            'price_tom' => 60,
            'feecallback_item_id' => 500053,
            'is_escalating_price' => false,
            'limit_per_server' => null,
            'tags' => ['Legendary', 'Pet Huyền Thoại', 'Bóng Tối'],
            'badge' => '🔥 MỚI NHẤT',
            'allow_gift' => false,
            'limit_per_user' => 1,
            'is_pet' => true,
            'pet_stats' => [
                ['label' => 'ATK Cộng', 'value' => '+15%', 'icon' => '⚔️'],
                ['label' => 'HP Cộng', 'value' => '+12%', 'icon' => '❤️'],
                ['label' => 'DEF Cộng', 'value' => '+10%', 'icon' => '🛡️'],
                ['label' => 'Phẩm Chất', 'value' => 'Truyền Thuyết', 'icon' => '⭐'],
                ['label' => 'Kỹ Năng', 'value' => 'Hắc Diệm / Đọa Ảnh', 'icon' => '🌑'],
                ['label' => 'Loại', 'value' => 'Tấn Công', 'icon' => '🐉'],
            ],
        ],

        // === DANH HIEU ban duoc (item 380xxx -> dung Lenh Bai -> nhan danh hieu, +luc chien VINH VIEN du deo hay khong). Giao qua GM-mail nhu Chi Ton. Gia ladder = lead-call, owner chinh duoc. ===
        'tom_title_hacam_tienphong' => [
            'id' => 'tom_title_hacam_tienphong', 'name' => 'Tiên Phong Hắc Ám',
            'description' => 'Danh hiệu vĩnh viễn (sở hữu là +lực chiến mãi mãi). Mở đầu bộ Hắc Ám 7 cấp. Nhận Lệnh Bài qua thư, dùng để kích hoạt. Mỗi nhân vật 1 lần.',
            'icon' => '⚔️', 'image' => null, 'price_wpoint' => null, 'price_wcoin' => null, 'price_tom' => 20,
            'game_item_id' => 380030, 'feecallback_item_id' => 380030,
            'tags' => ['Danh Hiệu', 'Bộ Hắc Ám', 'Vĩnh Viễn'], 'badge' => '🖤 HẮC ÁM', 'allow_gift' => false, 'limit_per_user' => 1, 'is_variable' => false,
        ],
        'tom_title_hacam_dausi' => [
            'id' => 'tom_title_hacam_dausi', 'name' => 'Đấu Sĩ Hắc Ám',
            'description' => 'Danh hiệu vĩnh viễn, cộng lực chiến. Cấp 2 bộ Hắc Ám. Nhận Lệnh Bài qua thư, dùng để kích hoạt. Mỗi nhân vật 1 lần.',
            'icon' => '🛡️', 'image' => null, 'price_wpoint' => null, 'price_wcoin' => null, 'price_tom' => 25,
            'game_item_id' => 380031, 'feecallback_item_id' => 380031,
            'tags' => ['Danh Hiệu', 'Bộ Hắc Ám', 'Vĩnh Viễn'], 'badge' => '🖤 HẮC ÁM', 'allow_gift' => false, 'limit_per_user' => 1, 'is_variable' => false,
        ],
        'tom_title_hacam_dungsi' => [
            'id' => 'tom_title_hacam_dungsi', 'name' => 'Dũng Sĩ Hắc Ám',
            'description' => 'Danh hiệu vĩnh viễn, cộng lực chiến. Cấp 3 bộ Hắc Ám. Nhận Lệnh Bài qua thư, dùng để kích hoạt. Mỗi nhân vật 1 lần.',
            'icon' => '⚔️', 'image' => null, 'price_wpoint' => null, 'price_wcoin' => null, 'price_tom' => 28,
            'game_item_id' => 380032, 'feecallback_item_id' => 380032,
            'tags' => ['Danh Hiệu', 'Bộ Hắc Ám', 'Vĩnh Viễn'], 'badge' => '🖤 HẮC ÁM', 'allow_gift' => false, 'limit_per_user' => 1, 'is_variable' => false,
        ],
        'tom_title_hacam_kysi' => [
            'id' => 'tom_title_hacam_kysi', 'name' => 'Kỵ Sĩ Hắc Ám',
            'description' => 'Danh hiệu vĩnh viễn, cộng lực chiến. Cấp 4 bộ Hắc Ám. Nhận Lệnh Bài qua thư, dùng để kích hoạt. Mỗi nhân vật 1 lần.',
            'icon' => '🐎', 'image' => null, 'price_wpoint' => null, 'price_wcoin' => null, 'price_tom' => 32,
            'game_item_id' => 380033, 'feecallback_item_id' => 380033,
            'tags' => ['Danh Hiệu', 'Bộ Hắc Ám', 'Vĩnh Viễn'], 'badge' => '🖤 HẮC ÁM', 'allow_gift' => false, 'limit_per_user' => 1, 'is_variable' => false,
        ],
        'tom_title_hacam_daisu' => [
            'id' => 'tom_title_hacam_daisu', 'name' => 'Đại Sư Hắc Ám',
            'description' => 'Danh hiệu vĩnh viễn, cộng lực chiến. Cấp 5 bộ Hắc Ám. Nhận Lệnh Bài qua thư, dùng để kích hoạt. Mỗi nhân vật 1 lần.',
            'icon' => '🔮', 'image' => null, 'price_wpoint' => null, 'price_wcoin' => null, 'price_tom' => 38,
            'game_item_id' => 380034, 'feecallback_item_id' => 380034,
            'tags' => ['Danh Hiệu', 'Bộ Hắc Ám', 'Vĩnh Viễn'], 'badge' => '🖤 HẮC ÁM', 'allow_gift' => false, 'limit_per_user' => 1, 'is_variable' => false,
        ],
        'tom_title_hacam_tongsu' => [
            'id' => 'tom_title_hacam_tongsu', 'name' => 'Tông Sư Hắc Ám',
            'description' => 'Danh hiệu vĩnh viễn, cộng lực chiến. Cấp 6 bộ Hắc Ám. Nhận Lệnh Bài qua thư, dùng để kích hoạt. Mỗi nhân vật 1 lần.',
            'icon' => '👑', 'image' => null, 'price_wpoint' => null, 'price_wcoin' => null, 'price_tom' => 45,
            'game_item_id' => 380035, 'feecallback_item_id' => 380035,
            'tags' => ['Danh Hiệu', 'Bộ Hắc Ám', 'Vĩnh Viễn'], 'badge' => '🖤 HẮC ÁM', 'allow_gift' => false, 'limit_per_user' => 1, 'is_variable' => false,
        ],
        'tom_title_hacam_vuonggia' => [
            'id' => 'tom_title_hacam_vuonggia', 'name' => 'Vương Giả Hắc Ám',
            'description' => 'Danh hiệu vĩnh viễn, cộng lực chiến. Đỉnh bộ Hắc Ám 7 cấp - đẳng cấp vương giả. Nhận Lệnh Bài qua thư, dùng để kích hoạt. Mỗi nhân vật 1 lần.',
            'icon' => '👑', 'image' => null, 'price_wpoint' => null, 'price_wcoin' => null, 'price_tom' => 55,
            'game_item_id' => 380036, 'feecallback_item_id' => 380036,
            'tags' => ['Danh Hiệu', 'Bộ Hắc Ám', 'Đỉnh Bộ'], 'badge' => '🖤 VƯƠNG GIẢ', 'allow_gift' => false, 'limit_per_user' => 1, 'is_variable' => false,
        ],
        'tom_title_ngaothi' => [
            'id' => 'tom_title_ngaothi', 'name' => 'Ngạo Thị Quần Hùng',
            'description' => 'Danh hiệu vĩnh viễn, cộng lực chiến. Khí phách coi thường quần hùng. Nhận Lệnh Bài qua thư, dùng để kích hoạt. Mỗi nhân vật 1 lần.',
            'icon' => '🔥', 'image' => null, 'price_wpoint' => null, 'price_wcoin' => null, 'price_tom' => 35,
            'game_item_id' => 380023, 'feecallback_item_id' => 380023,
            'tags' => ['Danh Hiệu', 'Lực Chiến', 'Vĩnh Viễn'], 'badge' => '⭐ DANH HIỆU', 'allow_gift' => false, 'limit_per_user' => 1, 'is_variable' => false,
        ],
        'tom_title_thiensu' => [
            'id' => 'tom_title_thiensu', 'name' => 'Thiên Sứ Giáng Lâm',
            'description' => 'Danh hiệu vĩnh viễn, cộng lực chiến. Hào quang thiên sứ giáng thế. Nhận Lệnh Bài qua thư, dùng để kích hoạt. Mỗi nhân vật 1 lần.',
            'icon' => '😇', 'image' => null, 'price_wpoint' => null, 'price_wcoin' => null, 'price_tom' => 35,
            'game_item_id' => 380024, 'feecallback_item_id' => 380024,
            'tags' => ['Danh Hiệu', 'Lực Chiến', 'Vĩnh Viễn'], 'badge' => '⭐ DANH HIỆU', 'allow_gift' => false, 'limit_per_user' => 1, 'is_variable' => false,
        ],
        'tom_title_kitichvuonggia' => [
            'id' => 'tom_title_kitichvuonggia', 'name' => 'Kì Tích Vương Giả',
            'description' => 'Danh hiệu vĩnh viễn, cộng lực chiến. Vương giả của những kì tích. Nhận Lệnh Bài qua thư, dùng để kích hoạt. Mỗi nhân vật 1 lần.',
            'icon' => '🏆', 'image' => null, 'price_wpoint' => null, 'price_wcoin' => null, 'price_tom' => 50,
            'game_item_id' => 380038, 'feecallback_item_id' => 380038,
            'tags' => ['Danh Hiệu', 'Lực Chiến', 'Vĩnh Viễn'], 'badge' => '👑 KÌ TÍCH', 'allow_gift' => false, 'limit_per_user' => 1, 'is_variable' => false,
        ],
    ],
];
